In [1]:
import torch 
import pandas as pd  
import numpy as np   
import matplotlib.pyplot as plt 


# Introduction to  Tensors

## Creating Tensors

In [2]:
# scalar  
scalar=torch.tensor(7)
scalar 

tensor(7)

In [3]:
scalar.ndim 

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector 
vector=torch.tensor([7,7])
vector


tensor([7, 7])

In [6]:
vector.shape # 1D tensor with 2 elements

torch.Size([2])

In [7]:
vector.ndim # number of dimensions

1

In [8]:
Matrix=torch.tensor([[7,7],[7,7]])
Matrix

tensor([[7, 7],
        [7, 7]])

In [9]:
Matrix.ndim

2

In [10]:
Matrix.shape

torch.Size([2, 2])

In [11]:
# TENSOR
Tensor=torch.tensor([[[1,2,3],[4,5,6]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [12]:
Tensor.ndim

3

In [13]:
Tensor.shape

torch.Size([1, 2, 3])

### Random Tensors

In [14]:
# Create a random tensor fo size (3,4)
random_tensor=torch.rand(3,3)
random_tensor

tensor([[0.1562, 0.3941, 0.8574],
        [0.4231, 0.6611, 0.6465],
        [0.3462, 0.7641, 0.7066]])

In [15]:
random_tensor.ndim 

2

In [16]:
random_tensor.shape

torch.Size([3, 3])

In [17]:
# Create a random tensor with similar shape to an image tensor
image_tensor=torch.rand(224,224,3) # height, width, color channels
image_tensor.shape,image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
image_tensor

tensor([[[0.4399, 0.7876, 0.2539],
         [0.8312, 0.7858, 0.6476],
         [0.1560, 0.5253, 0.3292],
         ...,
         [0.4017, 0.5799, 0.2743],
         [0.9984, 0.9271, 0.5800],
         [0.8194, 0.2839, 0.2792]],

        [[0.9956, 0.1035, 0.3034],
         [0.1362, 0.5933, 0.9589],
         [0.3760, 0.4044, 0.0608],
         ...,
         [0.6909, 0.4709, 0.4569],
         [0.7533, 0.9728, 0.7605],
         [0.9413, 0.4909, 0.3550]],

        [[0.9922, 0.5940, 0.0540],
         [0.3550, 0.2999, 0.6233],
         [0.3710, 0.1830, 0.4806],
         ...,
         [0.2756, 0.8478, 0.0452],
         [0.1336, 0.1796, 0.6078],
         [0.0709, 0.3050, 0.6068]],

        ...,

        [[0.4156, 0.6205, 0.0739],
         [0.6182, 0.9154, 0.7337],
         [0.9180, 0.3703, 0.4869],
         ...,
         [0.4864, 0.9716, 0.2182],
         [0.0031, 0.9599, 0.0306],
         [0.5874, 0.5783, 0.1088]],

        [[0.9199, 0.1042, 0.2768],
         [0.4655, 0.1026, 0.8074],
         [0.

In [19]:
## Zeroes and ones tensors  
zero=torch.zeros(size=(3,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
zero*random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
one=torch.ones(size=(3,3))     
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
one.dtype

torch.float32

In [23]:
## Creating a range of tensors and tensor-like
range_tensor=torch.arange(start=0,end=10,step=2)
range_tensor 

tensor([0, 2, 4, 6, 8])

In [24]:
# Creating tensor alike
ten=torch.zeros_like(input=range_tensor)
ten

tensor([0, 0, 0, 0, 0])

## Tensor Datatypes

In [25]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.int32)
float_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [26]:
float_32_tensor.dtype

torch.int32

In [27]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float32)
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
res=float_32_tensor*int_32_tensor

In [28]:
res

tensor([ 9., 36., 81.])

### Getting Info from tensors

In [29]:
t1=torch.rand(2,1)
t1

tensor([[0.3281],
        [0.6080]])

In [30]:
t1.dtype,t1.shape,t1.ndim

(torch.float32, torch.Size([2, 1]), 2)

In [31]:
t1.size()

torch.Size([2, 1])

In [32]:
print(t1.device)

cpu


### Manipulating tensors

#### Tensor operations include Addition,Subtraction,Multiplication(element-wise),Divison,Matrix multiplication.

In [33]:
tensor=torch.tensor([1,2,3])
tensor=tensor+10
tensor

tensor([11, 12, 13])

In [34]:
tensor=tensor*10
tensor

tensor([110, 120, 130])

In [35]:
tensor=tensor-10
tensor

tensor([100, 110, 120])

In [36]:
tensor=tensor/10
tensor

tensor([10., 11., 12.])

In [37]:
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
torch.mul(tensor1,10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor2,10)


tensor([14, 15, 16])

#### Matrix Multiplication

In [39]:
t1=torch.tensor([1,2,3])
t2=torch.tensor([4,5,6])
torch.mul(t1,t2)

tensor([ 4, 10, 18])

In [40]:
t3=torch.rand(3,4)
t4=torch.rand(4,4)
torch.matmul(t3,t4)

tensor([[1.1479, 0.7104, 1.1531, 0.9966],
        [1.1123, 0.7540, 1.0080, 0.8051],
        [1.0861, 1.0153, 1.4040, 1.4191]])

#### Shapes for matrix multiplication 

In [41]:
tensor_A=torch.tensor([[1,2,3],[4,5,6]])
tensor_B=torch.tensor([[7,8,9],[10,11,12]])


In [42]:
tensor_A.shape,tensor_B.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

#### A transpose switches the axes or dimensions of a given tensor.

In [43]:
tensor_B.T

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [44]:
tensor_B 

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [45]:
tensor_B.shape,tensor_B.T.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [46]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 50,  68],
        [122, 167]])

#### Finding the Min,Max,Mean,sum etc (tensor aggregation)

In [47]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [49]:
torch.max(x),x.max()

(tensor(90), tensor(90))

#### Find the mean

In [50]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [51]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [52]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Find the index of the maximum value and minimum value
x.argmax(),x.argmin()

(tensor(9), tensor(0))

In [54]:
x[1]

tensor(10)

#### Reshaping,Restacking,Squeezing and unsqueezing tensors


In [55]:
x=torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x.shape

torch.Size([9])

In [57]:
x_reshaped=x.reshape(3,3)

In [58]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
z=x.view(9,1)
z,z.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [60]:
### Changing z changes x (because a view of a tensor shares the same memory as the original tensor)


In [61]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
x = torch.zeros(2, 1, 2, 1, 2)
y=torch.squeeze(x)
x.size(),y.size() 



(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 2, 2]))

In [63]:
y_unsqueezed=y.unsqueeze(dim=3)
y_unsqueezed.size()

torch.Size([2, 2, 2, 1])

In [64]:
x=torch.randn(2,3,5)
x.size()
torch.permute(x,(2,0,1)).size()


torch.Size([5, 2, 3])

In [65]:
x_original=torch.rand(size=(224,224,3))
x_permuted=torch.permute(x_original,(2,0,1))

In [66]:
x_original

tensor([[[0.5278, 0.7378, 0.6080],
         [0.0839, 0.0495, 0.2033],
         [0.0799, 0.8706, 0.7849],
         ...,
         [0.0537, 0.4053, 0.3058],
         [0.7053, 0.6573, 0.0956],
         [0.9740, 0.3203, 0.1181]],

        [[0.5655, 0.0456, 0.4881],
         [0.7996, 0.8465, 0.5249],
         [0.1017, 0.6601, 0.4736],
         ...,
         [0.1266, 0.1212, 0.9178],
         [0.0362, 0.7930, 0.8265],
         [0.2593, 0.5850, 0.2598]],

        [[0.3825, 0.6980, 0.8983],
         [0.6343, 0.2147, 0.8897],
         [0.3536, 0.0135, 0.7471],
         ...,
         [0.3509, 0.3368, 0.7687],
         [0.6393, 0.0402, 0.9561],
         [0.5890, 0.5401, 0.2041]],

        ...,

        [[0.2577, 0.0540, 0.3194],
         [0.8673, 0.7439, 0.7440],
         [0.6006, 0.3763, 0.3567],
         ...,
         [0.0063, 0.7158, 0.1693],
         [0.4885, 0.6246, 0.3550],
         [0.1656, 0.9500, 0.0899]],

        [[0.8653, 0.4037, 0.2452],
         [0.2692, 0.6894, 0.8437],
         [0.

In [67]:
x_permuted

tensor([[[0.5278, 0.0839, 0.0799,  ..., 0.0537, 0.7053, 0.9740],
         [0.5655, 0.7996, 0.1017,  ..., 0.1266, 0.0362, 0.2593],
         [0.3825, 0.6343, 0.3536,  ..., 0.3509, 0.6393, 0.5890],
         ...,
         [0.2577, 0.8673, 0.6006,  ..., 0.0063, 0.4885, 0.1656],
         [0.8653, 0.2692, 0.5780,  ..., 0.1785, 0.0089, 0.4014],
         [0.7222, 0.3207, 0.1820,  ..., 0.5654, 0.1772, 0.4398]],

        [[0.7378, 0.0495, 0.8706,  ..., 0.4053, 0.6573, 0.3203],
         [0.0456, 0.8465, 0.6601,  ..., 0.1212, 0.7930, 0.5850],
         [0.6980, 0.2147, 0.0135,  ..., 0.3368, 0.0402, 0.5401],
         ...,
         [0.0540, 0.7439, 0.3763,  ..., 0.7158, 0.6246, 0.9500],
         [0.4037, 0.6894, 0.4701,  ..., 0.1251, 0.2058, 0.4611],
         [0.2368, 0.6429, 0.0963,  ..., 0.0354, 0.3153, 0.6885]],

        [[0.6080, 0.2033, 0.7849,  ..., 0.3058, 0.0956, 0.1181],
         [0.4881, 0.5249, 0.4736,  ..., 0.9178, 0.8265, 0.2598],
         [0.8983, 0.8897, 0.7471,  ..., 0.7687, 0.9561, 0.

#### Indexing (selecting data from tensors)

In [68]:
import torch 
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [70]:
x[0][0]

tensor([1, 2, 3])

In [71]:
x[0,0,1]

tensor(2)

In [72]:
x[:,:,2]

tensor([[3, 6, 9]])

#### Pytorch and Numpy

In [73]:
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
array.dtype

dtype('float64')

In [75]:
torch.arange(1.0,8.0)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [76]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [78]:
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [79]:
torch.rand(3,3)

tensor([[0.3319, 0.5188, 0.6192],
        [0.8479, 0.4064, 0.5429],
        [0.1952, 0.3205, 0.7608]])

In [80]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.2641, 0.9989, 0.7125, 0.1144],
        [0.4240, 0.3603, 0.6765, 0.8091],
        [0.1485, 0.5601, 0.5334, 0.5432]])
tensor([[0.3869, 0.0441, 0.4723, 0.6464],
        [0.7135, 0.8706, 0.7632, 0.4092],
        [0.8777, 0.2808, 0.6808, 0.4890]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [81]:
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_A=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A==random_tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [82]:
!nvidia-smi

Wed Jan 10 09:48:48 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.97                 Driver Version: 531.97       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650       WDDM | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8                6W /  N/A|      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

##### Check for GPU access using Pytorch

In [83]:
torch.cuda.is_available()

True

#### Set up device agnostic code

In [84]:
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [85]:
# Count number of devices  
torch.cuda.device_count()

1

#### Tensor operations on the GPU

In [86]:
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [87]:
tensor=tensor.to(device)
print(tensor,tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [88]:
#### Moving Tensors back to the CPU
tensor=tensor.cpu()

In [89]:
print(tensor.device)

cpu


In [90]:
##### We cannot convert the tensor to numpy if it is on GPU